name: test_app_talatix
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^1.4.0
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^0.13.6
  connectivity_plus: ^4.0.1
  encrypt: ^5.0.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/image/
    - assets/svg/
    - assets/fonts/
    - assets/rive/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

